name: Deploy Docs

# 触发条件
on:
  # 手动触发
  workflow_dispatch:
  # push 到指定分支
  push:
    branches:
      - main
    # 只在下列路径变更时触发
    paths:
      - "apps/docs/**"
      - "packages/**"

# 设置权限
permissions:
  contents: write

# 设置上海时区
env:
  TZ: Asia/Shanghai

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      # 设置 node 版本
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      # 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 构建 packages（文档依赖）
      - name: Build packages
        run: pnpm run build

      # 构建文档
      - name: Build docs
        run: pnpm run docs:build

      # 部署
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # GitHub Pages 读取的分支
          branch: gh-pages
          # Rspress 构建输出目录
          folder: apps/docs/doc_build
